### ISSUE TITLE
Log file is not being created

### ISSUE THREAD

**Issue by chris3ware** [tonedefdev/terracreds#15]
I have added an environment variable to store the config.yaml file in ~/.terracreds/ and have enabled logging:

`terracreds config view`

```yaml
logging:
  enabled: true
  path: ~/.terracreds/
```

However, after several `terraform plans` - where the credential_helper process is invoked  to retrieve the api key for terraform cloud - I am not seeing a log file in the .terracreds directory.

```zsh
2022-09-27T05:21:39.119+0100 [DEBUG] Attempting to open CLI config file: /Users/chris/.terraformrc
2022-09-27T05:21:39.119+0100 [INFO]  Loading CLI configuration from /Users/chris/.terraformrc
2022-09-27T05:21:39.121+0100 [DEBUG] checking for credentials in "/Users/chris/.terraform.d/plugins"
2022-09-27T05:21:39.121+0100 [WARN]  found legacy credentials "terraform-credentials-terracreds"
```

```zsh
➜  lsa ~/.terracreds
Permissions Size User  Date Modified Name
.rwxr-xr-x    48 chris 26 Sep 21:44  config.yaml
```

terracreds version: v2.1.0
terraform version: v1.3.0

**Comment by tonedefdev** [comment]
@chris3ware  - thanks for reporting this issue! The problem is that `terracreds` won't perform a tilda expansion to get the absolute path of the directory if a tilda is used to represent the `$HOME` directory.

If you were to switch to `/Users/chris/.terracreds/` it should work without issue. There are some updates I need to make on how `terracreds` handles paths in general, so I'll add a feature label to use the `filepath.Abs()` method to be able to resolve tilda and relative path expansion in the next release.

**Comment by chris3ware** [comment]
Ah, OK, thanks for the update. I'll try that and keep an eye out for the next release.
