### ISSUE TITLE
Use "store"+"forget" verbs instead of/in addition to "create"+"delete"

### ISSUE THREAD

**Issue by sirlatrom** [tonedefdev/terracreds#3]
https://www.terraform.io/docs/internals/credentials-helpers.html#how-terraform-runs-credentials-helpers states:

> The current set of verbs are:
>
> - get: retrieve the credentials for the given hostname
> - _**store**_: store new credentials for the given hostname
> - forget: delete any stored credentials for the given hostname

`terracreds` currently uses the ver `create` instead of `store`, and `delete` instead of `forget`. Maybe this is a change in the Terraform CLI itself.

**Comment by tonedefdev** [comment]
I tested last not and the aliases did not seem sufficient in getting `terraform login` to work properly with `terracreds`. From the documentation the `store` procedure needs to read a JSON token from STDIN which currently `terracreds` doesn't support. I'll be working on adding this feature shortly so that using `terraform login` works properly.
